# Site
name: "The CrossThink"
title: "The CrossThink"
description: "The CrossThink"
logo: 'assets/images/ctlogo2.png'
favicon: 'assets/images/ctlogo2.png'
baseurl: ''
google_analytics: 'UA-xxxxxxxx-1'
disqus: 'demowebsite'
mailchimp-list: 'https://wowthemes.us11.list-manage.com/subscribe/post?u=8aeb20a530e124561927d3bd8&amp;id=8c3d2d214b'
include: ["_pages"]
permalink: /:title/
email: cs.rep@ashoka.edu.in

# Authors
authors:
  tanvi:
    name: Tanvi Roy
    display_name: Tanvi Roy    
    avatar: 'assets/images/tanvi.png'
    email: tanvi.roy_ug22@ashoka.edu.in
    web: https://www.tanviroy.com
    description: "Student Editor-in-Chief"
  soham:
    name: Soham De
    display_name: Soham De
    avatar: 'assets/images/soham.png'
    email: soham.de_ug22@ashoka.edu.in
    web: https://www.sohamde.in
    twitter: https://twitter.com/actuallysoham
    description: "Associate Editor, CS Representative"
  uttamasha:
    name: Uttamasha Dutta
    display_name: Uttamasha Dutta
    avatar: 'assets/images/uttamasha.png'
    email: uttamasha.dutta_ug22@ashoka.edu.in
    web: https://www.linkedin.com/in/uttamasha-dutta-5552491b1/
    description: "Associate Editor, Anthro-Socio Representative"
  Khushi:
    name: Khushi Mehta
    display_name: Khushi Mehta
    avatar: 'assets/images/khushi.jpeg'
    web: https://www.linkedin.com/in/khushi-mehta-7a09661a1/
    email: khushi.mehta_ug22@ashoka.edu.in
    description: "Associate Editor, WiCS President"
  sohamb:
    name: Soham Bagchi
    display_name: Soham Bagchi
    avatar: 'assets/images/bagchi.png'
    web: https://www.linkedin.com/in/soham-bagchi/
    email: soham.bagchi_ug22@ashoka.edu.in
    description: "Associate Editor, CS Society President"

# Societies
societies:
  cssoc:
    name: CS Society
    display_name: The CS Society    
    avatar: 'assets/images/cssoc.png'
    email: cs.society@ashoka.edu.in
    web: https://www.cs-ashoka.github.io
    description: "Computer Science Society at Ashoka"
  wics:
    name: WiCS
    display_name: WiCS Ashoka
    avatar: 'assets/images/wics.png'
    email: wics@ashoka.edu.in
    web: https://www.wics-ashoka.github.io
    description: "Women in Computing Society at Ashoka"
  soa:
    name: SoA
    display_name: Jot
    avatar: 'assets/images/soa.png'
    email: anthroposoc@ashoka.edu.in
    web: https://anthroposoc.wordpress.com
    description: "Journal of the Sociology and Anthropology Society at Ashoka"
  phil:
    name: Phil
    display_name: Citta
    avatar: 'assets/images/citta.png'
    email: citta@ashoka.edu.in
    description: "Journal of the Philosophy Society at Ashoka"
  aues:
    name: AUES
    display_name: Ashoka University Economics Society
    avatar: 'assets/images/aues.png'
    email: econsoc@ashoka.edu.in
    web: https://www.ashokaeconsoc.com
    description: "Economics Society at Ashoka"

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-archives
  - jekyll-figure
    
# Archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: '/category/:name/'
    
# Pagination 
paginate: 6
paginate_path: /page:num/
    
# Other
highlighter: none
markdown: kramdown
kramdown:
   syntax_highlighter_opts:
      disable : true



# Adsense (change to "enabled" to activate, also your client id and ad slot. Create a new ad unit from your Adsense account to get the slot.)
adsense: "disabled"
adsense-data-ad-client: "ca-pub-3412143450191416"
adsense-data-ad-slot: "1363087678"

# Lazy Images ("enabled" or "disabled")
lazyimages: "disabled"

# Post Author Box ("enabled" or "disabled")
authorbox: "enabled"

# Sass
sass:
  sass_dir: _sass
  style: compressed

exclude: [changelog.md, LICENSE.txt, README.md, Gemfile, Gemfile.lock]